services:
  mysql:
    image: mysql:8.4
    container_name: cochunho_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cochunho_db
      MYSQL_USER: cochunho
      MYSQL_PASSWORD: cochunho_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
